import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FFF' },
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  containerAbas: { flex: 1 },
  scrollContent: { padding: 15, flexGrow: 1, paddingTop: 50 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  card: { backgroundColor: '#FFF', width: '48%', borderRadius: 15, padding: 12, marginBottom: 15, borderWidth: 1, borderColor: '#E1E8ED' },
  cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  statusBadge: { backgroundColor: '#4169E122', color: '#4169E1', fontSize: 10, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 10, fontWeight: '600' },
  iconContainer: { alignItems: 'center', justifyContent: 'center', height: 60, marginTop: 10 },
  cardTitle: { color: '#000', fontSize: 15, fontWeight: 'bold', textAlign: 'center', marginVertical: 10 },
  secaoTitulo: { fontSize: 18, fontWeight: 'bold', color: '#333', marginTop: 15, marginBottom: 10 },
  cardVazio: { backgroundColor: '#FFF', padding: 20, borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: '#E1E8ED' },
  txtVazio: { color: '#666', fontWeight: 'bold' },
  btnToggleCadastro: { flexDirection: 'row', backgroundColor: '#FFF', padding: 18, borderRadius: 12, alignItems: 'center', marginBottom: 10, borderWidth: 1, borderColor: '#4169E155', borderStyle: 'dashed' },
  txtToggleCadastro: { fontSize: 16, fontWeight: 'bold', color: '#4169E1', marginLeft: 10 },
  formulario: { backgroundColor: '#FFF', padding: 15, borderRadius: 12, borderWidth: 1, borderColor: '#E1E8ED', marginBottom: 15 },
  input: { backgroundColor: '#F1F3F5', padding: 12, borderRadius: 8, marginBottom: 10, fontSize: 14, color: '#000' },
  btnSalvar: { backgroundColor: '#4169E1', padding: 14, borderRadius: 8, alignItems: 'center' },
  btnSalvarTexto: { color: '#FFF', fontWeight: 'bold', fontSize: 15 },
  wrapperPaciente: { marginBottom: 10 },
  cardPacienteHome: { flexDirection: 'row', backgroundColor: '#FFF', padding: 15, borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: '#E1E8ED' },
  infoPacienteHome: { marginLeft: 15, flex: 1 },
  nomePacienteHome: { fontSize: 16, fontWeight: 'bold', color: '#000' },
  detalhesPacienteHome: { color: '#666', fontSize: 12 },
  containerAcoes: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#4169E122', borderBottomLeftRadius: 12, borderBottomRightRadius: 12, padding: 15, marginTop: -4 },
  topoAcoes: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  tituloAcoes: { fontSize: 13, fontWeight: 'bold', color: '#666' },
  gridAcoes: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  btnAcaoCard: { backgroundColor: '#F8F9FA', width: '48%', padding: 12, borderRadius: 10, alignItems: 'center', marginBottom: 10, borderWidth: 1, borderColor: '#E1E8ED' },
  btnAtivo: { borderColor: '#4169E1', backgroundColor: '#4169E111' },
  txtAcaoCard: { fontSize: 11, fontWeight: 'bold', color: '#333', marginTop: 5 },
  itemListaPaciente: { flexDirection: 'row', backgroundColor: '#FFF', padding: 15, borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: '#E1E8ED' },
  subAbaAtividade: { marginTop: 10, backgroundColor: '#F8F9FA', borderRadius: 8, padding: 12, borderWidth: 1, borderColor: '#E1E8ED' },
  subAbaHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  subAbaTitulo: { fontSize: 14, fontWeight: 'bold', color: '#4169E1' },
  calendarioContainer: { backgroundColor: '#FFF', borderRadius: 10, padding: 10, borderWidth: 1, borderColor: '#E1E8ED', marginBottom: 12 },
  calendarioHeaderNavegacao: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10, paddingHorizontal: 10 },
  btnSetas: { padding: 5, justifyContent: 'center', alignItems: 'center' },
  mesTitulo: { fontWeight: 'bold', color: '#333', fontSize: 16 },
  diasGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start' },
  diaBotao: { width: '13.5%', aspectRatio: 1, justifyContent: 'center', alignItems: 'center', margin: '0.7%', borderRadius: 6, backgroundColor: '#F1F3F5', position: 'relative' },
  diaSelecionado: { backgroundColor: '#4169E1' },
  diaComInfo: { backgroundColor: '#4169E122', borderWidth: 1, borderColor: '#4169E155' },
  diaTexto: { fontSize: 12, fontWeight: '500', color: '#333' },
  diaTextoSelecionado: { color: '#FFF', fontWeight: 'bold' },
  pontoIndicador: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#FF6347', position: 'absolute', bottom: 3 },
  legendaInputTitulo: { fontSize: 13, fontWeight: 'bold', color: '#555', marginBottom: 6, marginTop: 4 },
  textArea: { backgroundColor: '#FFF', padding: 10, borderRadius: 6, fontSize: 13, textAlignVertical: 'top', borderWidth: 1, borderColor: '#E1E8ED', color: '#000', minHeight: 70 },
  btnSalvarNota: { backgroundColor: '#4169E1', padding: 12, borderRadius: 6, alignItems: 'center', marginTop: 10 },
  btnSalvarNotaTexto: { color: '#FFF', fontSize: 14, fontWeight: 'bold' },
  bottomTab: { flexDirection: 'row', backgroundColor: '#FFF', paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#E1E8ED', justifyContent: 'space-around' },
  tabItem: { alignItems: 'center', flex: 1 },
  tabText: { fontSize: 11, color: '#000', marginTop: 4 },
  containerHistoricoLabels: { marginTop: 20, borderTopWidth: 1, borderTopColor: '#E1E8ED', paddingTop: 15 },
  tituloLinhaTempo: { fontSize: 14, fontWeight: 'bold', color: '#333', marginBottom: 12 },
  cardLabelHistorico: { backgroundColor: '#F8F9FA', padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#E1E8ED', borderLeftWidth: 4, marginBottom: 10 },
  labelHeaderHistorico: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  labelTagIcon: { flexDirection: 'row', alignItems: 'center' },
  txtTagLabel: { fontSize: 11, fontWeight: 'bold', marginLeft: 6 },
  btnEditarLabel: { padding: 4 },
  txtConteudoLabel: { fontSize: 13, color: '#222', lineHeight: 18 },

  // --- NOVOS ESTILOS EXCLUSIVOS DA TELA DE PERFIL ---
  headerPerfil: { flexDirection: 'row', backgroundColor: '#FFF', padding: 20, borderRadius: 15, borderWidth: 1, borderColor: '#E1E8ED', alignItems: 'center', marginBottom: 15 },
  avatarEsquerda: { width: 75, height: 75, borderRadius: 37.5, backgroundColor: '#4169E115', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#4169E133' },
  infoDireitaPerfil: { marginLeft: 20, flex: 1 },
  nomeCuidador: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  subtituloCuidador: { fontSize: 13, color: '#666', marginTop: 2, marginBottom: 8 },
  btnEditarPerfil: { flexDirection: 'row', backgroundColor: '#4169E1', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 6, alignItems: 'center', alignSelf: 'flex-start' },
  txtBtnEditarPerfil: { color: '#FFF', fontSize: 11, fontWeight: 'bold', marginLeft: 4 },
  cardSecaoPerfil: { backgroundColor: '#FFF', padding: 15, borderRadius: 12, borderWidth: 1, borderColor: '#E1E8ED', marginBottom: 15 },
  tituloSecaoPerfilContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, borderBottomWidth: 1, borderBottomColor: '#F1F3F5', paddingBottom: 6 },
  tituloSecaoPerfil: { fontSize: 14, fontWeight: 'bold', color: '#333', marginLeft: 8 },
  conteudoTextoPerfil: { fontSize: 13, color: '#555', lineHeight: 20, marginBottom: 4 },
  itemExperiencia: { marginBottom: 12, borderBottomWidth: 1, borderBottomColor: '#F8F9FA', paddingBottom: 8 },
  cargoExperiencia: { fontSize: 13, fontWeight: 'bold', color: '#4169E1' },
  periodoExperiencia: { fontSize: 11, color: '#999', marginVertical: 2 },
  detalheExperiencia: { fontSize: 12, color: '#555', lineHeight: 16 }
});

export default styles;