import { StyleSheet, Platform } from 'react-native';
import { radius, spacing, typography } from '../../../theme';

export const getStyles = (colors, primaryColor) =>
  StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.background },
    flex: { flex: 1 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: spacing.lg,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    nome: {
      ...typography.title3,
      fontWeight: 'bold',
      color: colors.textPrimary,
      marginLeft: spacing.md,
      flex: 1,
    },
    listaMensagens: { padding: spacing.lg, flexGrow: 1 },
    listaVazia: { justifyContent: 'center' },
    balaoMensagem: {
      maxWidth: '80%',
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm + 2,
      borderRadius: radius.lg,
      marginBottom: spacing.sm,
    },
    balaoMinhaMensagem: {
      alignSelf: 'flex-end',
      backgroundColor: primaryColor,
      borderBottomRightRadius: 4,
    },
    balaoOutraMensagem: {
      alignSelf: 'flex-start',
      backgroundColor: colors.surface,
      borderBottomLeftRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    textoMinhaMensagem: { ...typography.body, color: colors.textOnPrimary },
    textoOutraMensagem: { ...typography.body, color: colors.textPrimary },
    horaMinhaMensagem: {
      ...typography.caption2,
      color: colors.textOnPrimary,
      opacity: 0.85,
      marginTop: 4,
      alignSelf: 'flex-end',
    },
    horaOutraMensagem: {
      ...typography.caption2,
      color: colors.textTertiary,
      marginTop: 4,
      alignSelf: 'flex-end',
    },
    containerInput: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      paddingHorizontal: spacing.md,
      paddingTop: spacing.md,
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    input: {
      flex: 1,
      borderRadius: radius.full,
      paddingHorizontal: spacing.lg,
      paddingVertical: Platform.OS === 'ios' ? spacing.sm + 2 : spacing.sm,
      marginRight: spacing.sm,
      maxHeight: 120,
      color: colors.textPrimary,
      backgroundColor: colors.background,
      minHeight: 52,
      fontSize: 17,
    },
    botaoEnviar: {
      width: 44,
      height: 44,
      borderRadius: radius.full,
      backgroundColor: primaryColor,
      justifyContent: 'center',
      alignItems: 'center',
    },
    botaoEnviarDesabilitado: { opacity: 0.45 },
  });
